# Generated by Django 4.2.3 on 2023-07-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_captureip_servicecatalog_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecatalog',
            name='url',
        ),
    ]
