# Generated by Django 4.2.3 on 2023-07-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_captureurl_delete_captureip'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatalog',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
