# Generated by Django 4.2.3 on 2023-07-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicecatalog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecatalog',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
